name: NumenCode Fundamentals

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-plugin:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: winter_test
                options: >-
                    --health-cmd="mysqladmin ping --silent"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
                ports:
                    - 3306:3306
                volumes:
                    - my-datavolume:/var/lib/mysql

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2
                  extensions: mbstring, mysql, pdo, bcmath, intl
                  ini-values: post_max_size=256M, upload_max_filesize=256M
                  coverage: none

            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Copy .env.example to .env
              run: cp .env.example .env

            - name: Generate application key
              run: php artisan key:generate

            - name: Run database migrations
              env:
                  DB_CONNECTION: mysql
                  DB_HOST: 127.0.0.1
                  DB_PORT: 3306
                  DB_DATABASE: winter_test
                  DB_USERNAME: root
                  DB_PASSWORD: root
              run: php artisan winter:up

            - name: Run plugin tests
              env:
                  DB_CONNECTION: mysql
                  DB_HOST: 127.0.0.1
                  DB_PORT: 3306
                  DB_DATABASE: winter_test
                  DB_USERNAME: root
                  DB_PASSWORD: root
              run: php artisan winter:test -p NumenCode.Fundamentals
